### ISSUE TITLE
Align maps and vector elements?

### ISSUE THREAD

**Issue by derryl** [Ciebiada/clojure-indent#1]
The README seems to suggest that this is a feature, but I don't see it in the code anywhere. Are you planning to add this feature at some point? (Or perhaps you've found another package that supplies this functionality?) Thanks!

<img width="314" alt="views_cljs_ ___projects_starcity_odin" src="https://user-images.githubusercontent.com/484537/29329202-f04c41e0-81a9-11e7-8e78-a1aabbc825ff.png">

**Comment by Ciebiada** [comment]
The current feature is about aligning the keys.
In order to align the values we would have to scan and reformat the whole file on each keypress.
Have you seen that implemented somewhere successfully?
It would be nice indeed, but I have to think about how that would work.
